// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: scanner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SBOMScanner_CreateSBOM_FullMethodName = "/sbomscanner.v1.SBOMScanner/CreateSBOM"
	SBOMScanner_Health_FullMethodName     = "/sbomscanner.v1.SBOMScanner/Health"
)

// SBOMScannerClient is the client API for SBOMScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SBOMScannerClient interface {
	CreateSBOM(ctx context.Context, in *CreateSBOMRequest, opts ...grpc.CallOption) (*CreateSBOMResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type sBOMScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewSBOMScannerClient(cc grpc.ClientConnInterface) SBOMScannerClient {
	return &sBOMScannerClient{cc}
}

func (c *sBOMScannerClient) CreateSBOM(ctx context.Context, in *CreateSBOMRequest, opts ...grpc.CallOption) (*CreateSBOMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSBOMResponse)
	err := c.cc.Invoke(ctx, SBOMScanner_CreateSBOM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sBOMScannerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SBOMScanner_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SBOMScannerServer is the server API for SBOMScanner service.
// All implementations must embed UnimplementedSBOMScannerServer
// for forward compatibility.
type SBOMScannerServer interface {
	CreateSBOM(context.Context, *CreateSBOMRequest) (*CreateSBOMResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSBOMScannerServer()
}

// UnimplementedSBOMScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSBOMScannerServer struct{}

func (UnimplementedSBOMScannerServer) CreateSBOM(context.Context, *CreateSBOMRequest) (*CreateSBOMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSBOM not implemented")
}
func (UnimplementedSBOMScannerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSBOMScannerServer) mustEmbedUnimplementedSBOMScannerServer() {}
func (UnimplementedSBOMScannerServer) testEmbeddedByValue()                     {}

// UnsafeSBOMScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SBOMScannerServer will
// result in compilation errors.
type UnsafeSBOMScannerServer interface {
	mustEmbedUnimplementedSBOMScannerServer()
}

func RegisterSBOMScannerServer(s grpc.ServiceRegistrar, srv SBOMScannerServer) {
	// If the following call panics, it indicates UnimplementedSBOMScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SBOMScanner_ServiceDesc, srv)
}

func _SBOMScanner_CreateSBOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSBOMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SBOMScannerServer).CreateSBOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SBOMScanner_CreateSBOM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SBOMScannerServer).CreateSBOM(ctx, req.(*CreateSBOMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SBOMScanner_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SBOMScannerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SBOMScanner_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SBOMScannerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SBOMScanner_ServiceDesc is the grpc.ServiceDesc for SBOMScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SBOMScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sbomscanner.v1.SBOMScanner",
	HandlerType: (*SBOMScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSBOM",
			Handler:    _SBOMScanner_CreateSBOM_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SBOMScanner_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner.proto",
}
